name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2.0.0
      with:
      swift-version: 6.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
